language: csharp
solution: Dreetris.sln
os:
  - osx
env:
  global:
    - Configuration=Release

install:
  - wget -O MonoGame.pkg "http://teamcity.monogame.net/guestAuth/repository/download/MonoGame_PackageMacAndLinux/.lastSuccessful/MonoGame.pkg?branch_MonoGame=%3Cdefault%3E"
  - sudo installer -pkg "MonoGame.pkg" -target /

script:
  - msbuild ./Dreetris/Dreetris.csproj /p:Configuration=Release /v:d /t:Build
